apps/linode-marketplace-keplerbuilder/requirements.txt
apps/linode-marketplace-lamp/requirements.txt
apps/linode-marketplace-lemp/requirements.txt
apps/linode-marketplace-woocommerce/requirements.txt
apps/linode-marketplace-wordpress/requirements.txt

https://github.com/linode/ansible_linode/releases/tag/v0.16.1

update linode_api4 == 5.5.0

---

apps/linode-marketplace-keplerbuilder/requirements.txt
apps/linode-marketplace-lamp/requirements.txt
apps/linode-marketplace-lemp/requirements.txt
apps/linode-marketplace-woocommerce/requirements.txt
apps/linode-marketplace-wordpress/requirements.txt
deployment_scripts/linode-marketplace-woocommerce/woocommerce-deploy.sh

Merge Develop into Main

---

apps/linode-marketplace-wordpress/roles/lamp/templates/vhost.conf.j2

Fix old reference in apache conf

---

apps/linode-marketplace-keplerbuilder/requirements.txt
apps/linode-marketplace-lamp/requirements.txt
apps/linode-marketplace-lemp/requirements.txt
apps/linode-marketplace-woocommerce/requirements.txt
apps/linode-marketplace-wordpress/requirements.txt
apps/linode-marketplace-wordpress/roles/wordpress/tasks/main.yml

https://github.com/linode/ansible-specdoc/releases/tag/v0.0.14

update ansible-specdoc to version 0.0.14

---

apps/linode-marketplace-harbor/provision.yml
apps/linode-marketplace-harbor/roles/harbor/tasks/main.yml
apps/linode-marketplace-joplin/provision.yml
apps/linode-marketplace-joplin/roles/joplin/tasks/main.yml
apps/linode-marketplace-nirvashare/provision.yml
apps/linode-marketplace-nirvashare/roles/nirvashare/tasks/main.yml
apps/linode-marketplace-odoo/provision.yml
apps/linode-marketplace-odoo/roles/odoo/tasks/main.yml
apps/linode-marketplace-yacht/provision.yml
apps/linode-marketplace-yacht/roles/yacht/tasks/main.yml
deployment_scripts/linode-marketplace-docker/docker-deploy.sh
deployment_scripts/linode-marketplace-focalboard/focalboard-deploy.sh
deployment_scripts/linode-marketplace-harbor/harbor-deploy.sh
deployment_scripts/linode-marketplace-joplin/joplin-deploy.sh
deployment_scripts/linode-marketplace-keplerbuilder/keplerbuilder-deploy.sh
deployment_scripts/linode-marketplace-lamp/lamp-deploy.sh
deployment_scripts/linode-marketplace-lemp/lemp-deploy.sh
deployment_scripts/linode-marketplace-mc-ffmpeg-demo/mc-ffmpeg-demo-deploy.sh
deployment_scripts/linode-marketplace-mc-live-encoder-demo/mc-live-encoder-demo-deploy.sh
deployment_scripts/linode-marketplace-mc-p2-avc-demo/mc-p2-avc-demo-deploy.sh
deployment_scripts/linode-marketplace-mc-xavc-demo/mc-xavc-demo-deploy.sh
deployment_scripts/linode-marketplace-mc-xdcam-demo/mc-xdcam-demo-deploy.sh
deployment_scripts/linode-marketplace-nirvashare/nirvashare-deploy.sh
deployment_scripts/linode-marketplace-odoo/odoo-deploy.sh
deployment_scripts/linode-marketplace-peppermint/peppermint-deploy.sh
deployment_scripts/linode-marketplace-simplex-chat/simplex-deploy.sh
deployment_scripts/linode-marketplace-uptimekuma/uptimekuma-deploy.sh
deployment_scripts/linode-marketplace-woocommerce/woocommerce-deploy.sh
deployment_scripts/linode-marketplace-wordpress/wordpress-deploy.sh
deployment_scripts/linode-marketplace-yacht/yacht-deploy.sh

Move newer apps credentials to provision.yml
run playbooks with -v not -vvvv
Minimize the commented git clone to -b

move creds, adjust verbose, fix branch comment

---

apps/linode-marketplace-peppermint/README.md
apps/linode-marketplace-peppermint/roles/peppermint/templates/docker-compose.yaml
apps/linode-marketplace-peppermint/roles/peppermint/templates/nginx.conf.j2

fixing and closing https://github.com/akamai-compute-marketplace/marketplace-apps/pull/74

Fix Peppermint port

---

apps/linode-marketplace-mc-live-encoder-demo/provision.yml

password now being added to the vars file

[fix] Mc Live Encoder password fix

---

deployment_scripts/linode-marketplace-splunk/splunk-deploy.sh

[fix] Splunk git clone 

---

apps/linode-marketplace-mc-live-encoder-demo/provision.yml
deployment_scripts/linode-marketplace-splunk/splunk-deploy.sh

Updates splunk stackscript to resolve deployment error.

Develop into Main

---

apps/linode-marketplace-openvpn/requirements.txt

[fix] OpenVPN add dnspython to reqs

---

apps/linode_helpers/roles/update_pkgs/tasks/main.yml

Once this is resolved, we are good to move forward
https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQG-R6bil1_KnGrNhlmDfGeBqxPulG7NPS3y2X0ZcEptVQ==

Revert tmp fix

---

docs/CONTRIBUTING.md
docs/DEVELOPMENT.md

update documentation guidelines, credential locations

Update Documentation Requirements

---

apps/linode-marketplace-focalboard/collections.yml
apps/linode-marketplace-mastodon/collections.yml
apps/linode-marketplace-mc-p2-avc-demo/collections.yml
apps/linode-marketplace-mc-xavc-demo/collections.yml
apps/linode-marketplace-mc-xdcam-demo/collections.yml
apps/linode-marketplace-nextcloud/collections.yml
apps/linode-marketplace-odoo/collections.yml
apps/linode-marketplace-uptimekuma/collections.yml
apps/linode-marketplace-yacht/collections.yml

updates community.docker to treat upstream dependency failure.
https://github.com/ansible-collections/community.docker/issues/868

set community.docker to bugfix ver

---

apps/linode-marketplace-wordpress/roles/post/tasks/main.yml
deployment_scripts/linode-marketplace-wordpress/wordpress-deploy.sh

update wp udf conditional

---

apps/linode-marketplace-openbao/roles/common/tasks/ufw_rules.yml
apps/linode-marketplace-openbao/roles/openbao/defaults/main.yml

updated with latest stable version which is now out of beta

[update] Openbao GA launch

---

apps/linode-marketplace-passbolt/README.md

update passbolt community edition language

---

apps/linode_helpers/roles/sudouser/tasks/main.yml

This is backwards compatible with what we have now and allow new apps to call this role at post task.

Sudo User Sanitation Input

---

apps/linode-marketplace-valkey/README.md
deployment_scripts/linode-marketplace-valkey/valkey-deploy.sh

Version 8.0.1 - https://github.com/valkey-io/valkey/releases/tag/8.0.1

[update] Valkey version update

---

apps/linode-marketplace-jenkins/README.md
deployment_scripts/linode-marketplace-jenkins/jenkins-deploy.sh

version: 2.479 
https://www.jenkins.io/changelog-stable/#v2.479.1

[update] Jenkins latest LTS version update

---

apps/linode-marketplace-splunk/README.md
apps/linode-marketplace-splunk/roles/common/tasks/main.yml
apps/linode-marketplace-splunk/roles/splunk/tasks/main.yml

[fix] Splunk SSH tasks OCA-1434

---

apps/linode-marketplace-beef/README.md
apps/linode-marketplace-beef/collections.yml
apps/linode-marketplace-beef/requirements.txt
apps/linode-marketplace-beef/roles/beef/tasks/main.yml
deployment_scripts/linode-marketplace-beef/beef-deploy.sh

Updates Ruby and RubyGems version for latest BeeF deploy.

Update BeeF to 24.04 LTS

---

apps/linode-marketplace-beef/roles/post/tasks/main.yml
apps/linode-marketplace-openlitespeed-wordpress/roles/post/tasks/main.yml
apps/linode-marketplace-passbolt/roles/post/tasks/main.yml

owns creds with sudo user to prevent lockout

[fix] chown sudo creds

---

apps/linode-marketplace-uptimekuma/README.md
apps/linode-marketplace-uptimekuma/collections.yml
apps/linode-marketplace-uptimekuma/provision.yml
apps/linode-marketplace-uptimekuma/requirements.txt
apps/linode-marketplace-uptimekuma/roles/docker/tasks/main.yml
apps/linode-marketplace-uptimekuma/roles/post/tasks/main.yml
apps/linode-marketplace-uptimekuma/roles/uptimekuma/tasks/main.yml
deployment_scripts/linode-marketplace-uptimekuma/uptimekuma-deploy.sh

Offer latest Ubuntu for Uptime Kuma

[update] UptimeKuma Ubuntu 24.04LTS upgrade

---

apps/linode-marketplace-code-server/requirements.txt

addresses the dup dnspython & the dependabot pr 
https://github.com/akamai-compute-marketplace/marketplace-apps/pull/190

[Update] code-server requirments updates

---

deployment_scripts/linode-marketplace-cyberpanel/cyberpanel-deploy.sh

Modifies location of ansible venv to triage Cyberpanel deployment errors. 
ref OCA-1498

[Update] Cyberpanel Virtual ENV

---

apps/linode-marketplace-nodejs/.ansible-lint
apps/linode-marketplace-nodejs/.yamllint
apps/linode-marketplace-nodejs/README.md
apps/linode-marketplace-nodejs/ansible.cfg
apps/linode-marketplace-nodejs/collections.yml
apps/linode-marketplace-nodejs/provision.yml
apps/linode-marketplace-nodejs/requirements.txt
apps/linode-marketplace-nodejs/roles/common/tasks/main.yml
apps/linode-marketplace-nodejs/roles/common/tasks/ufw_rules.yml
apps/linode-marketplace-nodejs/roles/nodejs/files/sample_app.js
apps/linode-marketplace-nodejs/roles/nodejs/handlers/main.yml
apps/linode-marketplace-nodejs/roles/nodejs/tasks/main.yml
apps/linode-marketplace-nodejs/roles/nodejs/tasks/nginx.yml
apps/linode-marketplace-nodejs/roles/nodejs/tasks/nodejs.yml
apps/linode-marketplace-nodejs/roles/nodejs/tasks/sample_app.yml
apps/linode-marketplace-nodejs/roles/nodejs/templates/nginx.conf.j2
apps/linode-marketplace-nodejs/roles/nodejs/templates/node.service.j2
apps/linode-marketplace-nodejs/roles/post/tasks/main.yml
apps/linode-marketplace-nodejs/roles/post/templates/motd.j2
apps/linode-marketplace-nodejs/site.yml
deployment_scripts/linode-marketplace-nodejs/nodejs-deploy.sh

Creates a default nodejs sample app behind nginx reverse proxy.
```
Hello, World! This is my Node.js app being served behind an NGINX reverse proxy.
```

[Add] Nodejs Backport

---

apps/linode-marketplace-openvpn/requirements.txt

Certbot was failing due, updated to latest certbot and resolves the issue

[Fix] Openvpn certbot dependency (OCA-1503) 

---

docs/CONTRIBUTING.md
docs/DEVELOPMENT.md

[update] Contributing & Development guidelines

[Update] Contributing & Development guidelines

---

apps/linode-marketplace-secure-your-server/README.md
apps/linode-marketplace-secure-your-server/collections.yml
apps/linode-marketplace-secure-your-server/requirements.txt
apps/linode-marketplace-secure-your-server/site.yml
deployment_scripts/linode-marketplace-secure-your-server/secure-your-server-deploy.sh
deployment_scripts/linode-marketplace-secure-your-server/test-vars.sh

[Update] Secure your server Ubu 24 & CI

[Update] Secure your server Ubu 24 & CI
